name: module3_task3
on:
  push:
    tags:
      - 1.0.0
  schedule:
    - cron: '10 0 * * *'
jobs:
  module3_task3:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo module3_task2/setup.sh
      - run: cd module3_task3 && make help
      - run: cd module3_task3 && make build
      - run: cd module3_task3 && make post POST_NAME="name" PORT_TITLE="title"
      - run: cd module3_task3 && make unit-tests
      - run: cd module3_task3 && make integration-tests
      - run: cd module3_task3 && make validate
      - run: cd module3_task3 && npm install -g markdownlint-cli && make lint
      - run: cd module3_task3 && make package
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            module3_task3/awesome-website.zip
            module3_task3/DEPLOY.md

